[general]
import = [
    "~/.config/alacritty/themes/midnight_haze.toml"
]

[window]
decorations = "None"
padding = {x = 12, y = 12}

[font]
size = 12.0 

[font.normal]
family = "DroidSansM Nerd Font"
style = "Regular"

[font.bold]
family = "DroidSansM Nerd Font"
style = "Regular"

[font.italic]
family = "DroidSansM Nerd Font"
style = "Regular"

[font.bold_italic]
family = "DroidSansM Nerd Font"
style = "Regular"
